/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'foodly';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String APPLE_PAY = 'assets/apple_pay.json';
  static const String DARK_MAP_STYLE = 'assets/dark_map_style.json';
  static const String ABOUTAPP = 'assets/icons/aboutapp.svg';
  static const String DELUSER = 'assets/images/deluser.svg';
}
